"""add capability_probes

Revision ID: e38e1b2df840
Revises: b23423fbc34e
Create Date: 2026-07-10 17:14:39.399806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38e1b2df840'
down_revision: Union[str, Sequence[str], None] = 'b23423fbc34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_probes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('supports_tool_calling', sa.Boolean(), nullable=False),
    sa.Column('probed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url', 'model', name='uq_capability_probes_base_url_model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability_probes')
    # ### end Alembic commands ###
